name: Build container images
on:
  schedule:
    - cron: "10 1 * * 3"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12-rc"]
        debian_codename: ["bullseye", "bookworm"]
        task: ["black", "lint", "mypy", "unittest", "integration"]
        concurrency: ["build_containers"]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Set-up buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./tests/docker/${{ matrix.task }}.Dockerfile
          tags: ghcr.io/corvan/${{ matrix.task }}:${{ matrix.python_version }}-${{ matrix.debian_codename }}
          build-args: python_version=${{ matrix.python_version }}-${{ matrix.debian_codename }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
