name: build container images
on:
  schedule:
    - cron: "42 13 2 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12-rc"]
        debian_codename: ["buster", "bullseye"]
        #task: ["black", "lint", "mypy", "unittest", "integration"]
        task: ["black", "lint", "mypy"]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Set-up buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./tests/docker/${{ matrix.task }}.Dockerfile
          tags: Corvan/${{ matrix.task }}:${{ matrix.python_version }}-${{ matrix.debian_codename }}
          build-args: PYTHON_VERSION=${{ matrix.python_version }}-${{ matrix.debian_codename }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
